# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pretalx.person.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nick', models.CharField(help_text='Please use only characters in the latin alphabet, plus numbers and _-.', max_length=60, unique=True, validators=[pretalx.person.models.user.nick_validator], verbose_name='Nickname')),
                ('first_name', models.CharField(blank=True, help_text='Please enter your real first name.', max_length=120, null=True, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, help_text='Please enter your real last name.', max_length=120, null=True, verbose_name='Name')),
                ('email', models.EmailField(help_text='Your email address will be used for password resets and notification about your event/submissions.', max_length=254, verbose_name='E-Mail')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_orga', models.BooleanField(default=True, verbose_name='Organizes the event')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='event.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
