# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_mail',
            field=models.BooleanField(default=False, verbose_name='Receive mails from pretalx?'),
        ),
    ]
