# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-07 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20170407_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Please enter your real name.', max_length=120, null=True, verbose_name='Name'),
        ),
    ]
