# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20170908_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpermission',
            name='is_reviewer',
            field=models.BooleanField(default=False, verbose_name='May write reviews for this event'),
        ),
        migrations.AlterField(
            model_name='speakerprofile',
            name='biography',
            field=models.TextField(blank=True, help_text='You can use markdown here.', null=True, verbose_name='Biography'),
        ),
    ]
