# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_gravatar',
            field=models.BooleanField(default=False, help_text='If you have registered with an email address that has a gravatar account, we can retrieve your profile picture from there.', verbose_name='Retrieve profile picture via gravatar'),
        ),
    ]
