# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_speakerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pw_reset_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pw_reset_token',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
