# Generated by Django 2.0.3 on 2018-05-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_remove_event_permitted'),
        ('person', '0016_auto_20180425_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpermission',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventPermission',
        ),
    ]
