# Generated by Django 4.2.10 on 2024-03-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0029_alter_user_avatar_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_source",
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_license",
            field=models.CharField(max_length=999, null=True),
        ),
    ]
