# Generated by Django 4.2.11 on 2024-03-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0031_alter_user_avatar_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_source",
            field=models.TextField(null=True),
        ),
    ]
