# Generated by Django 5.1.1 on 2024-10-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0029_alter_user_avatar_thumbnail_and_more"),
        ("person", "0032_alter_user_avatar_source"),
    ]

    operations = []
