# Generated by Django 5.1.9 on 2025-09-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BankImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('pending', 'pending'),
                            ('running', 'running'),
                            ('error', 'error'),
                            ('completed', 'completed'),
                        ],
                        default='pending',
                        max_length=32,
                    ),
                ),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('imported', 'imported, unchecked'),
                            ('nomatch', 'no match'),
                            ('invalid', 'not valid'),
                            ('error', 'error'),
                            ('valid', 'valid'),
                            ('already', 'valid, already paid'),
                            ('discarded', 'manually discarded'),
                        ],
                        default='imported',
                        max_length=32,
                    ),
                ),
                ('message', models.TextField()),
                ('checksum', models.CharField(db_index=True, max_length=190)),
                ('payer', models.TextField(blank=True)),
                ('reference', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.CharField(max_length=50)),
                ('date_parsed', models.DateField(null=True)),
                ('iban', models.CharField(blank=True, max_length=250)),
                ('bic', models.CharField(blank=True, max_length=250)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RefundExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('testmode', models.BooleanField(default=False)),
                ('rows', models.TextField(default='[]')),
                ('downloaded', models.BooleanField(default=False)),
            ],
        ),
    ]
