# Generated by Django 5.1.9 on 2025-09-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('banktransfer', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankimportjob',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.event'),
        ),
        migrations.AddField(
            model_name='bankimportjob',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.organizer'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.event'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='import_job',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transactions',
                to='banktransfer.bankimportjob',
            ),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='order',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order'
            ),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.organizer'),
        ),
        migrations.AddField(
            model_name='refundexport',
            name='event',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='banktransfer_refund_exports',
                to='base.event',
            ),
        ),
        migrations.AddField(
            model_name='refundexport',
            name='organizer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='banktransfer_refund_exports',
                to='base.organizer',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='banktransaction',
            unique_together={('event', 'organizer', 'checksum')},
        ),
    ]
