# Generated by Django 5.1.9 on 2025-09-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownDomain',
            fields=[
                ('domainname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='base.event')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='base.organizer')),
            ],
            options={
                'verbose_name': 'Known domain',
                'verbose_name_plural': 'Known domains',
            },
        ),
    ]
