# Generated by Django 5.1.3 on 2024-12-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixhelpers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnail",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
