# Generated by Django 5.1.2 on 2024-10-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0005_exhibitorinfo_booth_id_exhibitorinfo_booth_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitorinfo',
            name='allow_lead_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibitorinfo',
            name='allow_voucher_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibitorinfo',
            name='lead_scanning_scope_by_device',
            field=models.BooleanField(default=False),
        ),
    ]
