# Generated by Django 5.1.2 on 2024-11-04 09:04

from django.db import migrations

def convert_booth_ids_to_string(apps, schema_editor):
    ExhibitorInfo = apps.get_model('exhibitors', 'ExhibitorInfo')
    Lead = apps.get_model('exhibitors', 'Lead')
    
    # Convert ExhibitorInfo booth_ids
    for exhibitor in ExhibitorInfo.objects.all():
        if exhibitor.booth_id is not None:
            exhibitor.booth_id = str(exhibitor.booth_id)
            exhibitor.save()
    
    # Convert Lead booth_ids
    for lead in Lead.objects.all():
        if lead.booth_id is not None:
            lead.booth_id = str(lead.booth_id)
            lead.save()

class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0010_alter_lead_booth_id_exhibitorsettings'),
    ]

    operations = [
        migrations.RunPython(convert_booth_ids_to_string, reverse_code=migrations.RunPython.noop),
    ]
