# Generated by Django 5.1.4 on 2025-02-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0011_alter_exhibitorinfo_booth_id_alter_lead_booth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='booth_id',
            field=models.CharField(max_length=100),
        ),
    ]
