# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0003_auto_20170225_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_duration', models.PositiveIntegerField(default=30, help_text='Default duration in minutes')),
                ('max_duration', models.PositiveIntegerField(default=60, help_text='Maximum duration in minutes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_types', to='event.Event')),
            ],
        ),
    ]
