# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_auto_20170225_0601'),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('state', models.CharField(choices=[('submitted', 'submitted'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='submitted', max_length=9)),
                ('description', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes for the organizer')),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='event.Event')),
                ('speakers', models.ManyToManyField(blank=True, null=True, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('submission_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='submission.SubmissionType')),
            ],
        ),
    ]
