# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170225_0601'),
        ('submission', '0002_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('default_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.SubmissionType')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='event.Event')),
            ],
        ),
    ]
