# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170225_0601'),
        ('submission', '0003_cfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=7)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='event.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='cfp',
            name='default_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='submission.SubmissionType'),
        ),
    ]
