# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20170225_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
