# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20170225_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfp',
            name='headline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cfp',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
