# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20170226_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.CharField(db_index=True, default='', max_length=16),
            preserve_default=False,
        ),
    ]
