# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_auto_20170226_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='default_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='variant',
            field=models.CharField(choices=[('number', 'number'), ('string', 'string'), ('text', 'text'), ('boolean', 'boolean'), ('choices', 'choices'), ('muliple_choice', 'muliple_choice')], default='string', max_length=14),
        ),
    ]
