# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_auto_20171004_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=i18nfield.fields.I18nCharField(blank=True, help_text='Will appear just like this text below the question input field.', max_length=200, null=True, verbose_name='help text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='target',
            field=models.CharField(choices=[('submission', 'per submission'), ('speaker', 'per speaker'), ('reviewer', 'for reviewers')], default='submission', help_text='Do you require an answer from every speaker or for every talk?', max_length=10, verbose_name='question type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='variant',
            field=models.CharField(choices=[('number', 'Number'), ('string', 'Text (one-line)'), ('text', 'Multi-line text'), ('boolean', 'Yes/No'), ('choices', 'Choose one from a list'), ('multiple_choice', 'Choose multiple from a list')], default='string', max_length=15),
        ),
    ]
