# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_auto_20170228_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfp',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
