# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 14:53
from __future__ import unicode_literals

from django.db import migrations
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_auto_20170407_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiontype',
            name='name',
            field=i18nfield.fields.I18nCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=i18nfield.fields.I18nCharField(max_length=200),
        ),
    ]
