# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-08 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_auto_20170407_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
