# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0013_auto_20170408_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='subtitle',
        ),
    ]
