# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0014_remove_submission_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='content_locale',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=32, verbose_name='Language of the submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('submitted', 'submitted'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('confirmed', 'confirmed'), ('canceled', 'canceled'), ('withdrawn', 'withdrawn')], default='submitted', max_length=9, verbose_name='Submission state'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='submission.SubmissionType', verbose_name='Type of submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
