# Generated by Django 2.0.3 on 2018-06-19 20:22

from django.db import migrations, models
import pretalx.submission.models.submission


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0024_auto_20180619_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='review_code',
            field=models.CharField(blank=True, default=pretalx.submission.models.submission.generate_invite_code, max_length=32, null=True, unique=True),
        ),
    ]
