# Generated by Django 2.0.8 on 2018-08-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0025_auto_20180619_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum allowed text length in characters', null=True, verbose_name='Maximum text length'),
        ),
        migrations.AddField(
            model_name='question',
            name='min_length',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum allowed text length in characters', null=True, verbose_name='Minimum text length'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content_locale',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], default='en', max_length=32, verbose_name='Language of the submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('submitted', 'submitted'), ('accepted', 'accepted'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('canceled', 'canceled'), ('withdrawn', 'withdrawn'), ('deleted', 'deleted')], default='submitted', max_length=9, verbose_name='Submission state'),
        ),
    ]
