# Generated by Django 2.0.8 on 2018-09-22 10:11

from django.db import migrations, models
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0027_auto_20180812_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfp',
            name='text',
            field=i18nfield.fields.I18nTextField(blank=True, help_text='You can use <a href="https://docs.pretalx.org/en/latest/user/markdown.html" target="_blank" rel="noopener">Markdown</a> here.', null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='review',
            field=models.TextField(help_text='You can use <a href="https://docs.pretalx.org/en/latest/user/markdown.html" target="_blank" rel="noopener">Markdown</a> here.', verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='abstract',
            field=models.TextField(blank=True, help_text='A concise summary of your talk in one or two sentences. You can use <a href="https://docs.pretalx.org/en/latest/user/markdown.html" target="_blank" rel="noopener">Markdown</a> here.', null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True, help_text='A full-text description of your talk and its contents. You can use <a href="https://docs.pretalx.org/en/latest/user/markdown.html" target="_blank" rel="noopener">Markdown</a> here.', null=True, verbose_name='Description'),
        ),
    ]
