# Generated by Django 2.1.3 on 2018-11-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0029_auto_20181009_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Notes by the organiser for themselves (not visible for the speaker and the public) You can use <a href="https://docs.pretalx.org/en/latest/user/markdown.html" target="_blank" rel="noopener">Markdown</a> here.', null=True, verbose_name='Notes by the organiser'),
        ),
    ]
