# Generated by Django 2.1.5 on 2019-02-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0030_auto_20181209_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tracks',
            field=models.ManyToManyField(blank=True, help_text='You can limit this question to some tracks. Leave this field empty to apply to all tracks.', related_name='questions', to='submission.Track', verbose_name='Tracks'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum allowed text lenght in characters or words (set in CfP settings).', null=True, verbose_name='Maximum text length'),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_length',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum allowed text in characters or words (set in CfP settings).', null=True, verbose_name='Minimum text length'),
        ),
    ]
