# Generated by Django 2.1.5 on 2019-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0032_question_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='slot_count',
            field=models.PositiveIntegerField(default=1, help_text='How many times this talk will be held.', verbose_name='Slot Count'),
        ),
    ]
