# Generated by Django 2.1.5 on 2019-03-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20190224_0856'),
        ('submission', '0034_submission_internal_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Phase start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Phase end')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('can_review', models.BooleanField(default=True, verbose_name='Reviewers can write and edit reviews')),
                ('can_see_other_reviews', models.CharField(choices=[('always', 'Always'), ('never', 'Never'), ('after_review', 'After reviewing the submission')], default='after_review', max_length=12, verbose_name='Reviewers can see other reviews')),
                ('can_see_speaker_names', models.BooleanField(default=True, verbose_name='Reviewers can see speaker names')),
                ('can_change_submission_state', models.BooleanField(default=False, verbose_name='Reviewers can accept and reject submissions')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_phases', to='event.Event')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
