# Generated by Django 2.2.1 on 2019-05-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0038_auto_20190429_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
