# Generated by Django 2.2.7 on 2019-11-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0041_auto_20191105_0042"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_visible_to_reviewers",
            field=models.BooleanField(default=True),
        ),
    ]
