# Generated by Django 2.2.9 on 2020-01-24 12:13

from django.db import migrations, models
import pretalx.submission.models.resource


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0042_question_is_visible_to_reviewers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="resource",
            field=models.FileField(
                upload_to=pretalx.submission.models.resource.resource_path
            ),
        ),
    ]
