# Generated by Django 2.2.9 on 2020-02-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0043_auto_20200124_1213"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="anonymised_data",
            field=models.TextField(blank=True, default="{}", null=True),
        ),
    ]
