# Generated by Django 3.0.3 on 2020-03-01 19:25

from django.db import migrations
import i18nfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0044_submission_anonymised_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="help_text",
            field=i18nfield.fields.I18nCharField(blank=True, max_length=800, null=True),
        ),
    ]
