# Generated by Django 3.0.5 on 2020-06-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0022_auto_20200124_1213"),
        ("submission", "0047_track_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="submissiontype", unique_together={("event", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="track", unique_together={("event", "name")},
        ),
    ]
