# Generated by Django 3.1.8 on 2021-06-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0057_auto_20210508_1308"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="required",
        ),
    ]
