# Generated by Django 3.2.4 on 2021-12-02 23:02

from django.db import migrations, models
import pretalx.submission.models.cfp


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0060_alter_answeroption_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfp",
            name="fields",
            field=models.JSONField(
                default=pretalx.submission.models.cfp.default_fields
            ),
        ),
        migrations.AddField(
            model_name="cfp",
            name="settings",
            field=models.JSONField(
                default=pretalx.submission.models.cfp.default_settings
            ),
        ),
    ]
