# Generated by Django 3.2.10 on 2022-01-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0064_slot_count_min_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="slot_count",
            field=models.IntegerField(default=1),
        ),
    ]
