# Generated by Django 3.2.10 on 2022-01-24 01:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submission", "0065_alter_submission_slot_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewphase",
            name="proposal_visibility",
            field=models.CharField(default="all", max_length=8),
        ),
        migrations.AddField(
            model_name="submission",
            name="assigned_reviewers",
            field=models.ManyToManyField(
                related_name="assigned_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
