# Generated by Django 3.1.4 on 2021-01-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0022_filter_information_by_type_and_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerinformation",
            name="target_group",
            field=models.CharField(default="accepted", max_length=11),
        ),
    ]
