# Generated by Django 4.2.4 on 2023-10-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0026_alter_user_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerinformation",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="speakerinformation",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="speakerprofile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="speakerprofile",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
