# Generated by Django 5.1.2 on 2024-10-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0028_user_avatar_thumbnail_user_avatar_thumbnail_tiny"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_thumbnail",
            field=models.ImageField(null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_thumbnail_tiny",
            field=models.ImageField(null=True, upload_to="avatars/"),
        ),
    ]
