name: eventyay-next

services:
  web:
    build: ./app
    platform: linux/amd64
    container_name: eventyay-next-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/eventyay:/usr/src/app/eventyay
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  worker:
    build: ./app
    platform: linux/amd64
    container_name: eventyay-next-worker
    entrypoint: celery -A eventyay worker -l info
    volumes:
      - ./app/eventyay:/usr/src/app/eventyay
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    platform: linux/amd64
    container_name: eventyay-next-redis
    restart: unless-stopped
    volumes:
      - rd:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  db:
    image: postgres:15
    platform: linux/amd64
    container_name: eventyay-next-db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_data_dev:
  rd:
