# Generated by Django 4.2.13 on 2024-06-26 08:41

import django.db.models.deletion
import i18nfield.fields
from django.db import migrations, models

import pretix.base.models.base
import pretix.base.models.fields


def set_can_manage_customers(apps, schema_editor):
    Team = apps.get_model('pretixbase', 'Team')
    Team.objects.filter(can_change_organizer_settings=True).update(can_manage_customers=True)
    Team.objects.filter(can_change_orders=True, all_events=True).update(can_manage_customers=True)


class Migration(migrations.Migration):
    dependencies = [
        ('pretixbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(db_index=True, max_length=190, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=190, null=True)),
                ('password', models.CharField(max_length=128)),
                ('name_cached', models.CharField(max_length=255)),
                ('name_parts', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('locale', models.CharField(default='en', max_length=50)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers',
                                                to='pretixbase.Organizer')),
            ],
            options={
                'unique_together': {('organizer', 'email')},
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders',
                                    to='pretixbase.Customer'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_manage_customers',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            set_can_manage_customers,
            migrations.RunPython.noop,
        ),

        migrations.CreateModel(
            name='CustomerSSOProvider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', i18nfield.fields.I18nCharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('button_label', i18nfield.fields.I18nCharField(max_length=200)),
                ('method', models.CharField(max_length=190)),
                ('configuration', models.JSONField()),
                ('organizer',
                models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_providers',
                                   to='pretixbase.organizer')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.AddField(
            model_name='customer',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers',
                                    to='pretixbase.customerssoprovider'),
        ),
        migrations.CreateModel(
            name='CustomerSSOClient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('client_id', models.CharField(db_index=True, default=pretix.base.models.customers.generate_client_id,
                                               max_length=100, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('client_type', models.CharField(default='confidential', max_length=32)),
                ('authorization_grant_type', models.CharField(default='authorization-code', max_length=32)),
                ('redirect_uris', models.TextField()),
                ('allowed_scopes',
                 pretix.base.models.fields.MultiStringField(default=['openid', 'profile', 'email', 'phone'])),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_clients',
                                                to='pretixbase.organizer')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.AlterField(
            model_name='customer',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers',
                                    to='pretixbase.customerssoprovider'),
        ),
        migrations.CreateModel(
            name='CustomerSSOGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('nonce', models.CharField(max_length=255, null=True)),
                ('auth_time', models.IntegerField()),
                ('expires', models.DateTimeField()),
                ('redirect_uri', models.TextField()),
                ('scope', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants',
                                             to='pretixbase.customerssoclient')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_grants',
                                               to='pretixbase.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSSOAccessToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_code', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('scope', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens',
                                             to='pretixbase.customerssoclient')),
                ('customer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_access_tokens',
                                   to='pretixbase.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='external_identifier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
