# Generated by Django 4.2.13 on 2024-06-28 10:31

from django.db import migrations, models
import django.db.models.deletion
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "pretixbase",
            "0002_alter_cachedcombinedticket_id_alter_cachedticket_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizerFooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("label", i18nfield.fields.I18nCharField(max_length=200)),
                ("url", models.URLField()),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer_links",
                        to="pretixbase.organizer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventFooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("label", i18nfield.fields.I18nCharField(max_length=200)),
                ("url", models.URLField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer_links",
                        to="pretixbase.event",
                    ),
                ),
            ],
        ),
    ]
