# Generated by Django 4.2.13 on 2024-06-26 04:36

import django.db.models.deletion
import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0002_question_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerFooterLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('label', i18nfield.fields.I18nCharField(max_length=255)),
                ('url', models.URLField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='pretixbase.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='EventFooterLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('label', i18nfield.fields.I18nCharField(max_length=255)),
                ('url', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='pretixbase.event')),
            ],
        ),
    ]
