# Generated by Django 4.2.16 on 2024-10-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pretixbase', '0002_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_video_creation',
            field=models.BooleanField(default=False),
        )
    ]
