# Generated by Django 4.2.16 on 2024-10-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0004_create_customer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_video_create',
            field=models.BooleanField(default=False),
        ),
    ]
