# Generated by Django 5.1.3 on 2024-12-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pretixbase",
            "0005_alter_cachedcombinedticket_id_alter_cachedticket_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="Asia/Bangkok", max_length=100),
        ),
    ]
