# Generated by Django 4.2.16 on 2024-10-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0005_event_add_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="is_video_create",
            new_name="is_video_creation",
        )
    ]
