# Generated by Django 5.1.7 on 2025-03-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pretixbase', '0008_cartposition_job_title_orderposition_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wikimedia_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
