# Generated by Django 5.1.11 on 2025-08-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0010_add_room_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='gates',
            field=models.ManyToManyField(related_name='rooms', to='pretixbase.gate'),
        ),
    ]
