# Generated by Django 5.1.11 on 2025-08-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0011_add_gates_to_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceRoomPermission',
        ),
    ]
