# Generated by Django 4.2.11 on 2024-05-08 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownDomain',
            fields=[
                ('domainname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='pretixbase.event')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='pretixbase.organizer')),
            ],
            options={
                'verbose_name': 'Known domain',
                'verbose_name_plural': 'Known domains',
            },
        ),
    ]
