# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170225_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateField(verbose_name='Event start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Event end date'),
        ),
    ]
