# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import pretalx.event.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_update_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_css',
            field=models.FileField(blank=True, help_text='Upload a custom CSS file if changing the primary color is not sufficient for you.', null=True, upload_to=pretalx.event.models.event.event_css_path, verbose_name='Custom Event CSS'),
        ),
    ]
