# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_custom_css'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='color',
            new_name='primary_color',
        ),
    ]
