# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170226_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Event start date'),
        ),
    ]
