# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 14:43
from __future__ import unicode_literals

from django.db import migrations
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20170228_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=i18nfield.fields.I18nCharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle',
            field=i18nfield.fields.I18nCharField(blank=True, max_length=200, null=True, verbose_name='Subitle'),
        ),
    ]
