# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 10:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20170906_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(default='event@localhost', help_text='Will be used as sender/reply-to in emails', max_length=254, verbose_name='Orga email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='Should be short, only contain lowercase letters and numbers, and must be unique, as it is used in URLs.', validators=[django.core.validators.RegexValidator(message='The slug may only contain letters, numbers, dots and dashes.', regex='^[a-zA-Z0-9.-]+$')], verbose_name='Short form'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle',
            field=i18nfield.fields.I18nCharField(blank=True, help_text='A tagline, or motto, or description. Not mandatory.', max_length=200, null=True, verbose_name='Subtitle'),
        ),
    ]
