# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20170407_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='locale_array',
            field=models.TextField(default='en'),
        ),
    ]
