# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import pretalx.event.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20170924_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.FileField(blank=True, help_text="Upload your event's logo, if it is suitable to be displayed in the frontend's header.", null=True, upload_to=pretalx.event.models.event.event_logo_path, verbose_name='Logo'),
        ),
    ]
