# Generated by Django 2.0.3 on 2018-05-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20180407_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='subtitle',
        ),
    ]
