# Generated by Django 2.1.7 on 2019-03-29 19:49

from django.db import migrations, models
import pretalx.event.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20190224_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to=pretalx.event.models.event.event_logo_path),
        ),
    ]
