# Generated by Django 2.1.7 on 2019-03-29 19:49

from django.db import migrations, models
import pretalx.event.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20190224_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='header_image',
            field=models.FileField(blank=True, help_text="If you provide a header image, it will be displayed instead of your event's color and/or header pattern on top of all event pages. It will be center-aligned, so when the window shrinks, the center parts will continue to be displayed, and not stretched.", null=True, upload_to=pretalx.event.models.event.event_logo_path, verbose_name='Header image'),
        ),
    ]
