# Generated by Django 2.2 on 2019-04-29 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_event_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('#([0-9A-Fa-f]{3}){1,2}')]),
        ),
    ]
