# Generated by Django 3.2.4 on 2021-12-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0026_team_force_hide_speaker_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="custom_domain",
            field=models.URLField(null=True),
        ),
    ]
