# Generated by Django 4.2.4 on 2023-09-17 09:01

from django.db import migrations
from django.db.models import Q


def fix_locale_codes(apps, schema_editor):
    Event = apps.get_model("event", "Event")
    for event in Event.objects.filter(
        Q(locale_array__contains="zh")
        | Q(content_locale_array__contains="zh")
        | Q(locale__contains="zh")
    ):
        for attr in ["locale", "locale_array", "content_locale_array"]:
            locale_attr = getattr(event, attr)
            if "zh-TW" in locale_attr:
                locale_attr = locale_attr.replace("zh-TW", "zh-Hant")
            if "zh-CN" in locale_attr:
                locale_attr = locale_attr.replace("zh-CN", "zh-Hans")
            setattr(event, attr, locale_attr)
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0032_alter_event_timezone"),
    ]

    operations = [
        migrations.RunPython(
            fix_locale_codes,
            migrations.RunPython.noop,  # Fixing a bug, so we're not reverting
        ),
    ]
