FROM python:3.11-bookworm

COPY requirements.txt /requirements.txt
RUN apt update && apt install -y poppler-utils && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip3 install -U pip wheel setuptools && pip3 install -Ur requirements.txt
ENV VENUELESS_COMMIT_SHA=devcontainer
WORKDIR /app
EXPOSE 8375

