# Generated by Django 3.0.5 on 2020-10-02 14:04

from django.db import migrations, models

import venueless.storage.models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_storedfile_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedfile",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=999,
                null=True,
                upload_to=venueless.storage.models.storedfile_name,
            ),
        ),
    ]
