# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20170225_0749'),
        ('schedule', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talks', to='schedule.Room')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talks', to='schedule.Schedule')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='submission.Submission')),
            ],
        ),
    ]
