# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20170523_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkslot',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='talks', to='schedule.Room'),
        ),
    ]
