# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_talkslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='order',
            new_name='position',
        ),
    ]
