# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0006_auto_20170228_0941'),
        ('schedule', '0004_auto_20170225_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to='event.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
