# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 14:43
from __future__ import unicode_literals

from django.db import migrations
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=i18nfield.fields.I18nCharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=i18nfield.fields.I18nCharField(max_length=100),
        ),
    ]
