# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20170806_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to='schedule.Room'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
