# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20171001_1358'),
        ('schedule', '0010_auto_20171001_0439'),
    ]

    operations = [
    ]
