# Generated by Django 3.0.3 on 2020-03-21 18:01

from django.db import migrations
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0013_auto_20191107_1748"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="comment",
            field=i18nfield.fields.I18nTextField(blank=True, null=True),
        ),
    ]
