# Generated by Django 5.2.5 on 2025-10-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('thumb', models.FileField(max_length=255, upload_to='pub/thumbs/')),
            ],
            options={
                'unique_together': {('source', 'size')},
            },
        ),
    ]
