# Generated by Django 4.2.11 on 2024-05-08 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paypal', '0001_initial'),
        ('pretixbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedpaypalobject',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.order'),
        ),
        migrations.AddField(
            model_name='referencedpaypalobject',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.orderpayment'),
        ),
    ]
