# Generated by Django 5.1.3 on 2024-12-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banktransfer", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankimportjob",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="refundexport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
