# Generated by Django 5.2.5 on 2025-09-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='can_change_items',
            new_name='can_change_products',
        ),
        migrations.AlterUniqueTogether(
            name='event_settingsstore',
            unique_together={('object', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='globalsettings_settingsstore',
            unique_together={('key',)},
        ),
        migrations.AlterUniqueTogether(
            name='globalsettingsobject_settingsstore',
            unique_together={('key',)},
        ),
        migrations.AlterUniqueTogether(
            name='organizer_settingsstore',
            unique_together={('object', 'key')},
        ),
    ]
