# Generated by Django 5.2.5 on 2025-09-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_event_created_event_updated_organizer_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='is_orga_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='data',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
