# Generated by Django 5.2.5 on 2025-10-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_logentry_is_orga_action_alter_logentry_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='can_change_items',
            new_name='can_change_products',
        ),
    ]
