# Generated by Django 5.2.5 on 2025-10-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_streamingserver_event_config_event_domain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="data",
            field=models.TextField(default="{}"),
        ),
    ]
