# Generated by Django 6.0.7 on 2026-08-27 22:45

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def normalize_legacy_vouchers(apps, schema_editor):
    Voucher = apps.get_model('base', 'Voucher')
    InvoiceVoucher = apps.get_model('base', 'InvoiceVoucher')
    Voucher.objects.filter(budget__lt=Decimal('0.00')).update(budget=Decimal('0.00'))
    Voucher.objects.filter(value__lt=Decimal('0.00')).update(value=Decimal('0.00'))
    Voucher.objects.filter(price_mode='percent', value__gt=Decimal('100.00')).update(value=Decimal('100.00'))
    InvoiceVoucher.objects.filter(budget__lt=Decimal('0.00')).update(budget=Decimal('0.00'))
    InvoiceVoucher.objects.filter(value__lt=Decimal('0.00')).update(value=Decimal('0.00'))
    InvoiceVoucher.objects.filter(price_mode='percent', value__gt=Decimal('100.00')).update(value=Decimal('100.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_taxrule_tax_rate_bounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='budget',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='This is the maximum monetary amount that will be discounted using this voucher across all usages. If this is sum reached, the voucher can no longer be used.',
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                verbose_name='Maximum discount budget',
            ),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='value',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                verbose_name='Voucher value',
            ),
        ),
        migrations.AlterField(
            model_name='invoicevoucher',
            name='budget',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Maximum monetary amount that will be waived using this voucher across all usages. Leave empty for no budget limit.',
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                verbose_name='Maximum fee waiver budget',
            ),
        ),
        migrations.AlterField(
            model_name='invoicevoucher',
            name='value',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                verbose_name='Fee waiver value',
            ),
        ),
        migrations.RunPython(
            normalize_legacy_vouchers,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(
                condition=models.Q(budget__isnull=True) | models.Q(budget__gte=Decimal('0.00')),
                name='voucher_budget_gte_zero',
            ),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(
                condition=models.Q(value__isnull=True) | models.Q(value__gte=Decimal('0.00')),
                name='voucher_value_gte_zero',
            ),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(
                condition=~models.Q(price_mode='percent') | models.Q(value__isnull=True) | models.Q(value__lte=Decimal('100.00')),
                name='voucher_percent_value_lte_100',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoicevoucher',
            constraint=models.CheckConstraint(
                condition=models.Q(budget__isnull=True) | models.Q(budget__gte=Decimal('0.00')),
                name='invoice_voucher_budget_gte_zero',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoicevoucher',
            constraint=models.CheckConstraint(
                condition=models.Q(value__isnull=True) | models.Q(value__gte=Decimal('0.00')),
                name='invoice_voucher_value_gte_zero',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoicevoucher',
            constraint=models.CheckConstraint(
                condition=~models.Q(price_mode='percent') | models.Q(value__isnull=True) | models.Q(value__lte=Decimal('100.00')),
                name='invoice_voucher_percent_value_lte_100',
            ),
        ),
    ]
