# Generated by Django 6.0.7 on 2026-09-05

import django.db.models.deletion
import eventyay.base.models.loungemesh
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_taxrule_tax_rate_bounds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreamingServer',
        ),
        migrations.CreateModel(
            name='LoungeMeshAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('token', models.CharField(default=eventyay.base.models.loungemesh.default_token, max_length=128, unique=True)),
                ('moderator', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LoungeMeshServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField(max_length=300)),
                ('api_secret', models.CharField(blank=True, max_length=300)),
                ('jitsi_app_id', models.CharField(blank=True, max_length=200)),
                ('jitsi_app_secret', models.CharField(blank=True, max_length=300)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameIndex(
            model_name='gmailoauthcredential',
            new_name='base_gmailo_event_i_133776_idx',
            old_name='base_gmailo_event_i_6f0d0d_idx',
        ),
        migrations.RenameIndex(
            model_name='gmailoauthcredential',
            new_name='base_gmailo_is_acti_22cf9d_idx',
            old_name='base_gmailo_is_acti_0d8f8f_idx',
        ),
        migrations.AlterField(
            model_name='invoicevoucher',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monetary amount that will be waived using this voucher across all usages. Leave empty for no budget limit.', max_digits=10, null=True, verbose_name='Maximum fee waiver budget'),
        ),
        migrations.AlterField(
            model_name='invoicevoucher',
            name='max_usages',
            field=models.PositiveIntegerField(default=1, help_text='How many times this voucher can be redeemed.', verbose_name='Maximum redemptions'),
        ),
        migrations.AlterField(
            model_name='invoicevoucher',
            name='price_mode',
            field=models.CharField(choices=[('none', 'No effect'), ('set', 'Set product price to'), ('subtract', 'Subtract from product price'), ('percent', 'Reduce product price by (%)')], default='none', max_length=100, verbose_name='Waiver type'),
        ),
        migrations.AlterField(
            model_name='invoicevoucher',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fee waiver value'),
        ),
        migrations.AlterField(
            model_name='streamschedule',
            name='stream_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('hls', 'HLS')], default='youtube', max_length=50, verbose_name='Stream Type'),
        ),
        migrations.AlterField(
            model_name='team',
            name='can_video_manage_content',
            field=models.BooleanField(default=False, help_text='Create and edit stages and chat/video channels; edit and delete rooms.', verbose_name='Video: Can manage rooms and content'),
        ),
        migrations.AddField(
            model_name='loungemeshaccesstoken',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loungemesh_tokens', to='base.event'),
        ),
        migrations.AddField(
            model_name='loungemeshaccesstoken',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loungemesh_tokens', to='base.room'),
        ),
        migrations.AddField(
            model_name='loungemeshaccesstoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loungemesh_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loungemeshserver',
            name='event_exclusive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.event'),
        ),
        migrations.AddIndex(
            model_name='loungemeshaccesstoken',
            index=models.Index(fields=['token', 'expires'], name='base_lounge_token_82a916_idx'),
        ),
        migrations.AddField(
            model_name='bbbserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='bbb_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='bbbserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='bbb_servers', to='base.organizer'),
        ),
        migrations.AddField(
            model_name='janusserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='janus_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='janusserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='janus_servers', to='base.organizer'),
        ),
        migrations.AddField(
            model_name='jitsiserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='jitsi_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='jitsiserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='jitsi_servers', to='base.organizer'),
        ),
        migrations.AddField(
            model_name='loungemeshserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='loungemesh_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='loungemeshserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='loungemesh_servers', to='base.organizer'),
        ),
        migrations.AddField(
            model_name='turnserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='turn_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='turnserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='turn_servers', to='base.organizer'),
        ),
    ]
