# Generated by Django 6.0.7 on 2026-09-10 07:54

from django.db import migrations, models


INDEX_RENAMES = (
    ("base_gmailo_event_i_6f0d0d_idx", "base_gmailo_event_i_133776_idx"),
    ("base_gmailo_is_acti_0d8f8f_idx", "base_gmailo_is_acti_22cf9d_idx"),
)


def _index_exists(schema_editor, index_name):
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == "postgresql":
            cursor.execute("SELECT 1 FROM pg_class WHERE relname = %s", [index_name])
            return cursor.fetchone() is not None
        if schema_editor.connection.vendor == "sqlite":
            cursor.execute(
                "SELECT 1 FROM sqlite_master WHERE type = 'index' AND name = %s",
                [index_name],
            )
            return cursor.fetchone() is not None
    return False


def rename_gmail_indexes_forward(apps, schema_editor):
    for old_name, new_name in INDEX_RENAMES:
        if _index_exists(schema_editor, new_name):
            continue
        if not _index_exists(schema_editor, old_name):
            continue
        schema_editor.execute(
            f"ALTER INDEX {schema_editor.quote_name(old_name)} "
            f"RENAME TO {schema_editor.quote_name(new_name)}"
        )


def rename_gmail_indexes_backward(apps, schema_editor):
    for old_name, new_name in INDEX_RENAMES:
        if _index_exists(schema_editor, old_name):
            continue
        if not _index_exists(schema_editor, new_name):
            continue
        schema_editor.execute(
            f"ALTER INDEX {schema_editor.quote_name(new_name)} "
            f"RENAME TO {schema_editor.quote_name(old_name)}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0070_alter_voucher_budget_alter_voucher_value"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    rename_gmail_indexes_forward,
                    rename_gmail_indexes_backward,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="gmailoauthcredential",
                    new_name="base_gmailo_event_i_133776_idx",
                    old_name="base_gmailo_event_i_6f0d0d_idx",
                ),
                migrations.RenameIndex(
                    model_name="gmailoauthcredential",
                    new_name="base_gmailo_is_acti_22cf9d_idx",
                    old_name="base_gmailo_is_acti_0d8f8f_idx",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="invoicevoucher",
            name="max_usages",
            field=models.PositiveIntegerField(
                default=1,
                help_text="How many times this voucher can be redeemed.",
                verbose_name="Maximum redemptions",
            ),
        ),
        migrations.AlterField(
            model_name="invoicevoucher",
            name="price_mode",
            field=models.CharField(
                choices=[
                    ("none", "No effect"),
                    ("set", "Set product price to"),
                    ("subtract", "Subtract from product price"),
                    ("percent", "Reduce product price by (%)"),
                ],
                default="none",
                max_length=100,
                verbose_name="Waiver type",
            ),
        ),
        migrations.AlterField(
            model_name="streamschedule",
            name="stream_type",
            field=models.CharField(
                choices=[
                    ("youtube", "YouTube"),
                    ("vimeo", "Vimeo"),
                    ("hls", "HLS"),
                ],
                default="youtube",
                max_length=50,
                verbose_name="Stream Type",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="can_video_manage_content",
            field=models.BooleanField(
                default=False,
                help_text="Create and edit stages and chat/video channels; edit and delete rooms.",
                verbose_name="Video: Can manage rooms and content",
            ),
        ),
    ]
