# Generated by Django 6.0.7 on 2026-09-06 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_alter_voucher_budget_alter_voucher_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Short machine name, e.g. "google-analytics". Used to match blocked scripts.', max_length=100, unique=True, verbose_name='Service identifier')),
                ('title', models.CharField(max_length=200, verbose_name='Display name')),
                ('provider', models.CharField(blank=True, max_length=200, verbose_name='Provider')),
                ('purpose', models.TextField(blank=True, verbose_name='Description / purpose')),
                ('category', models.CharField(blank=True, choices=[('necessary', 'Strictly necessary'), ('functional', 'Functional'), ('analytics', 'Analytics'), ('marketing', 'Marketing'), ('embed', 'Embedded content')], default='', max_length=20, verbose_name='Consent category')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('privacy_policy_url', models.CharField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Privacy policy URL')),
                ('cookie_names', models.TextField(blank=True, help_text='One cookie name per line.', verbose_name='Cookie names')),
            ],
            options={
                'verbose_name': 'Third-party service',
                'verbose_name_plural': 'Third-party services',
                'ordering': ('category', 'title'),
            },
        ),
    ]
