# Generated by Django 5.2.16 on 2026-09-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_admin_message_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminemailqueue',
            name='recipient_count_snapshot',
            field=models.PositiveIntegerField(default=0, verbose_name='Recipient count at save time'),
        ),
    ]
