# Generated by Django 3.2.4 on 2021-12-02 23:02

from django.db import migrations, models
import pretalx.event.models.event


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0026_team_force_hide_speaker_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="custom_domain",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="display_settings",
            field=models.JSONField(
                default=pretalx.event.models.event.default_display_settings
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="feature_flags",
            field=models.JSONField(
                default=pretalx.event.models.event.default_feature_flags
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="mail_settings",
            field=models.JSONField(
                default=pretalx.event.models.event.default_mail_settings
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="review_settings",
            field=models.JSONField(
                default=pretalx.event.models.event.default_review_settings
            ),
        ),
    ]
