# Generated by Django 5.1.3 on 2024-12-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0036_alter_event_header_image_alter_event_logo"),
        ("mail", "0013_mailtemplate_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="accept_template",
        ),
        migrations.RemoveField(
            model_name="event",
            name="ack_template",
        ),
        migrations.RemoveField(
            model_name="event",
            name="question_template",
        ),
        migrations.RemoveField(
            model_name="event",
            name="reject_template",
        ),
        migrations.RemoveField(
            model_name="event",
            name="update_template",
        ),
    ]
