# Generated by Django 5.1.7 on 2025-05-04 01:06

import pretalx.event.models.organiser
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0038_eventextralink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teaminvite",
            name="token",
            field=models.CharField(
                default=pretalx.event.models.organiser.generate_invite_token,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
