# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import i18nfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0011_auto_20170419_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', i18nfield.fields.I18nCharField(max_length=200)),
                ('text', i18nfield.fields.I18nTextField()),
                ('reply_to', models.EmailField(blank=True, help_text='Change the Reply-To address if you do not want to use the default orga address', max_length=200, null=True, verbose_name='Reply-To')),
                ('log_address', models.EmailField(blank=True, help_text='You can choose to receive one notification mail for every batch of mails sent from this template.', max_length=200, null=True, verbose_name='Log address')),
                ('bcc', models.CharField(blank=True, help_text='Enter comma separated addresses. Will receive a blind copy of every mail sent from this template. This may be a LOT!', max_length=1000, null=True, verbose_name='BCC')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mail_templates', to='event.Event')),
            ],
        ),
    ]
