# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=1000)),
                ('reply_to', models.CharField(max_length=1000)),
                ('cc', models.CharField(max_length=1000)),
                ('bcc', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queued_mails', to='event.Event')),
            ],
        ),
    ]
