# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-21 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_queuedmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedmail',
            name='bcc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='queuedmail',
            name='cc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
