# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_queuedmail_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject',
            field=i18nfield.fields.I18nCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='text',
            field=i18nfield.fields.I18nTextField(),
        ),
        migrations.AlterField(
            model_name='queuedmail',
            name='bcc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='queuedmail',
            name='cc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='queuedmail',
            name='reply_to',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='queuedmail',
            name='sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queuedmail',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='queuedmail',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='queuedmail',
            name='to',
            field=models.CharField(max_length=1000),
        ),
    ]
