# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-23 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20170421_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtemplate',
            name='log_address',
        ),
    ]
