# Generated by Django 3.2.4 on 2021-08-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0007_auto_20190327_2241"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplate",
            name="is_auto_created",
            field=models.BooleanField(default=False),
        ),
    ]
