# Generated by Django 4.2.4 on 2023-10-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0010_queuedmail_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="mailtemplate",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="queuedmail",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="queuedmail",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
