# Generated by Django 5.1.2 on 2024-10-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0011_created_updated_everywhere"),
        ("submission", "0077_answeroption_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuedmail",
            name="submissions",
            field=models.ManyToManyField(
                related_name="mails", to="submission.submission"
            ),
        ),
    ]
