name: eventyay

services:
  web:
    image: eventyay/eventyay-next:enext
    container_name: eventyay-next-web
    build:
      context: ../app
      dockerfile: Dockerfile.prod
    command: gunicorn eventyay.config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./data/static:/home/app/web/static
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: eventyay-next-db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env
  watchtower:
    image: containrrr/watchtower
    container_name: eventyay-next-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      WATCHTOWER_NOTIFICATIONS: 'shoutrrr'
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: eventyay-next
      WATCHTOWER_POLL_INTERVAL: 600
      WATCHTOWER_NOTIFICATION_URL: ${WATCHTOWER_NOTIFICATION_URL}
    command: watchtower eventyay-next-web --cleanup

