# Generated by Django 5.1.10 on 2025-07-07 16:48

import django.db.models.deletion
import i18nfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0010_alter_cachedcombinedticket_id_alter_cachedticket_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('to_users', models.JSONField(null=True)),
                ('composing_for', models.CharField(default='attendees', max_length=20)),
                ('raw_subject', i18nfield.fields.I18nTextField(null=True)),
                ('raw_message', i18nfield.fields.I18nTextField(null=True)),
                ('filters', models.JSONField(null=True)),
                ('reply_to', models.CharField(max_length=100, null=True)),
                ('bcc', models.TextField(null=True)),
                ('locale', models.CharField(max_length=16, null=True)),
                ('attachments', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_mails', to='pretixbase.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
