# Generated by Django 5.1.10 on 2025-07-02 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0010_alter_cachedcombinedticket_id_alter_cachedticket_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('raw_subject', models.TextField(null=True)),
                ('raw_message', models.TextField(null=True)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('reply_to', models.CharField(max_length=1000, null=True)),
                ('bcc', models.TextField(null=True)),
                ('locale', models.CharField(max_length=16, null=True)),
                ('attachments', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_mails', to='pretixbase.event')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.order')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pretixbase.orderposition')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
