# Generated by Django 5.1.7 on 2025-06-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedmail',
            name='raw_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='queuedmail',
            name='raw_subject',
            field=models.TextField(null=True),
        ),
    ]
