# Generated by Django 6.0.7 on 2026-09-01 21:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0004_emailqueue_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueuefilter',
            name='exclude_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailqueuefilter',
            name='permission_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='emailqueuefilter',
            name='specific_people',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='emailqueuefilter',
            name='status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='emailqueuefilter',
            name='team_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
