# Generated by Django 6.0.7 on 2026-09-07 05:18

import django.db.models.deletion
import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_alter_voucher_budget_alter_voucher_value'),
        ('sendmail', '0005_emailqueuefilter_exclude_me_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', i18nfield.fields.I18nCharField(max_length=200, verbose_name='Subject')),
                ('text', i18nfield.fields.I18nTextField(verbose_name='Message')),
                ('reply_to', models.CharField(blank=True, default='', help_text='Change the Reply-To address if you do not want to use the default organiser address', max_length=200, verbose_name='Reply-To')),
                ('bcc', models.CharField(blank=True, default='', help_text='Enter comma separated addresses. Will receive a blind copy of every mail sent from this template. This may be a LOT!', max_length=1000, verbose_name='BCC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_mail_templates', to='base.event')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
    ]
