version: '3'
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile-dev
        ports:
            - "8375:8375"
        volumes:
            - ./server:/app:ro
            - appdata:/data
        environment:
            - VENUELESS_DB_TYPE=postgresql
            - VENUELESS_DB_NAME=venueless
            - VENUELESS_DB_USER=venueless
            - VENUELESS_DB_PASS=venueless
            - VENUELESS_DB_HOST=db
            - VENUELESS_REDIS_HOST=redis
            - VENUELESS_DATA_DIR=/data
            - VENUELESS_MEDIA_URL=http://localhost:8375/media/
            - VENUELESS_REDIS_USE_PUBSUB=true
        entrypoint: ["bash", "/app/docker-dev-entrypoint.sh"]
        depends_on:
            - db
            - redis
    celery:
        build:
            context: ./server
            dockerfile: Dockerfile-dev
        volumes:
            - ./server:/app:ro
            - appdata:/data
        environment:
            - VENUELESS_DB_TYPE=postgresql
            - VENUELESS_DB_NAME=venueless
            - VENUELESS_DB_USER=venueless
            - VENUELESS_DB_PASS=venueless
            - VENUELESS_DB_HOST=db
            - VENUELESS_REDIS_HOST=redis
            - VENUELESS_DATA_DIR=/data
            - VENUELESS_MEDIA_URL=http://localhost:8375/media/
        entrypoint: ["bash", "/app/docker-dev-entrypoint-celery.sh"]
        depends_on:
            - db
            - redis
    webapp:
        build:
            context: ./webapp
            dockerfile: Dockerfile-dev
        ports:
            - "8880:8880"
        volumes:
            - ./webapp:/app:ro
        command: ["npm", "start", "--", "--host", "0.0.0.0"]
    redis:
        image: "redis:latest"
    db:
        image: "postgres:11"
        ports:
            - "5438:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=venueless
            - POSTGRES_PASSWORD=venueless
volumes:
    postgres_data:
    appdata:
networks:
  default:
    ipam:
      config:
        - subnet: 172.177.0.0/16

