# Generated by Django 3.2.10 on 2022-07-19 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("event", "0029_event_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenuelessSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("token", models.TextField(null=True)),
                ("url", models.URLField(null=True)),
                ("return_url", models.TextField(null=True)),
                ("last_push", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venueless_settings",
                        to="event.event",
                    ),
                ),
            ],
        ),
    ]
