# Generated by Django 4.2.14 on 2024-09-16 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0001_initial'),
        ('exhibitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitorinfo',
            name='lead_scanning_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExhibitorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('exhibitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_assignments', to='exhibitors.exhibitorinfo')),
                ('item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibitor_assignment', to='pretixbase.item')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
