name: Build

on:
  push:
    branches: [ development ]
    paths-ignore:
      - 'src/pretalx/locale/**'
      - 'doc/**'
  pull_request:
    branches: [ development ]
    paths-ignore:
      - 'src/pretalx/locale/**'
      - 'doc/**'

permissions:
  contents: read  #  to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  packaging:
    runs-on: ubuntu-latest
    name: Packaging
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./src/pretalx/frontend/schedule-editor
      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y gettext unzip
      - name: Install Python dependencies
        run: uv sync
      - name: Run check-manifest
        run: uv run --no-sync check-manifest
      - name: Run build
        run: uv build
      - name: Check package
        run: uvx twine check dist/*
      - name: Check files to make sure we ship our frontend
        run: unzip -l dist/pretalx*whl | grep frontend || exit 1
      - name: Check files to make sure we ship our frontend but not our node_modules
        run: unzip -l dist/pretalx*whl | grep node_modules && exit 1 || exit 0
      - name: Install the created wheel package with pip
        run: |
          # Switch to a new virtualenv
          python -m venv test_venv
          test_venv/bin/python -m pip install dist/pretalx*whl
      - name: Make sure we can run pretalx commands
        run: test_venv/bin/python -m pretalx help
      - name: Make sure we can run through all migrations
        run: test_venv/bin/python -m pretalx migrate
