import importlib.util
import logging

from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerSplitView,
)

import eventyay.control.urls
import eventyay.eventyay_common.urls
import eventyay.presale.urls
from eventyay.api.views.stripe import stripe_webhook_view
from eventyay.base.views import cachedfiles, csp, health, js_catalog, js_helpers, metrics, redirect
from eventyay.control.views import pages
from eventyay.eventyay_common.views import auth
from eventyay.eventyay_common.views.custom import ConfirmEmailView, SignupView

logger = logging.getLogger(__name__)

# Stripe payment plugin webhook compatibility (#2463).
# Stripe Dashboard often posts to /tickets/_stripe/webhook (and without a trailing
# slash). The plugin only registers `/_stripe/webhook/`, so those URLs 404 or
# 301-redirect — both fail Stripe delivery. These aliases hit the same handler.
_stripe_webhook_aliases = []
try:
    from eventyay_stripe.views import webhook as stripe_payment_webhook

    _stripe_webhook_aliases = [
        re_path(
            r'^_stripe/webhook/?$',
            stripe_payment_webhook,
            name='stripe-payment-webhook-compat',
        ),
        re_path(
            r'^tickets/_stripe/webhook/?$',
            stripe_payment_webhook,
            name='stripe-payment-webhook-tickets-compat',
        ),
    ]
except ImportError:
    logger.debug('eventyay_stripe not installed; skipping Stripe webhook path aliases')

_paypal_webhook_aliases = []
try:
    from eventyay_paypal.views import webhook as paypal_payment_webhook

    _paypal_webhook_aliases = [
        re_path(
            r'^_paypal/webhook/?$',
            paypal_payment_webhook,
            name='paypal-payment-webhook-compat',
        ),
        re_path(
            r'^tickets/_paypal/webhook/?$',
            paypal_payment_webhook,
            name='paypal-payment-webhook-tickets-compat',
        ),
    ]
except ImportError:
    logger.debug('eventyay_paypal not installed; skipping PayPal webhook path aliases')


base_patterns = [
    path(
        'download/<id>/',
        cachedfiles.DownloadView.as_view(),
        name='cachedfile.download',
    ),
    path('healthcheck/', health.healthcheck, name='healthcheck'),
    path('redirect/', redirect.redir_view, name='redirect'),
    path(
        'jsi18n/<slug:lang>/',
        js_catalog.js_catalog,
        name='javascript-catalog',
    ),
    path('metrics/', metrics.serve_metrics, name='metrics'),
    path('csp_report/', csp.csp_report, name='csp.report'),
    path('js_helpers/states/', js_helpers.states, name='js_helpers.states'),
    path(
        'api/v1/schema/',
        SpectacularAPIView.as_view(api_version='api-v1'),
        name='api-schema',
    ),
    path(
        'api/v1/docs/',
        SpectacularSwaggerSplitView.as_view(url_name='api-schema'),
        name='api-swagger-ui',
    ),
    path(
        'api/v1/redoc/',
        SpectacularRedocView.as_view(url_name='api-schema'),
        name='api-redoc',
    ),
    path('api/v1/', include(('eventyay.api.urls', 'eventyayapi'), namespace='api-v1')),
    # Billing Stripe webhook also under the legacy /tickets/ API prefix some
    # environments document in the Stripe Dashboard.
    re_path(
        r'^tickets/api/v1/webhook/stripe/?$',
        stripe_webhook_view,
        name='stripe-billing-webhook-tickets-compat',
    ),
    *_stripe_webhook_aliases,
    *_paypal_webhook_aliases,
    # Override django-allauth's confirm email view at the same URL and name
    # Using the exact path and name ('account_confirm_email') ensures email links
    # generated by allauth resolve to our custom Jinja-based view.
    path('accounts/confirm-email/<str:key>/', ConfirmEmailView.as_view(), name='account_confirm_email'),
    # Override django-allauth's signup view at the same URL and name so all
    # account_signup references in the app route to our customized Jinja view.
    path('accounts/signup/', SignupView.as_view(), name='account_signup'),
    path('accounts/', include('allauth.urls')),
    path('login/', auth.login, name='auth.login'),
    path('login/2fa/', auth.Login2FAView.as_view(), name='auth.login.2fa'),
]

control_patterns = [
    path('control/', include((eventyay.control.urls, 'control'))),
]

eventyay_common_patterns = [
    path('common/', include((eventyay.eventyay_common.urls, 'common'), namespace='common')),
]


page_patterns = [
    path('terms/', pages.SystemPageView.as_view(slug='terms'), name='page.terms'),
    path('privacy/', pages.SystemPageView.as_view(slug='privacy'), name='page.privacy'),
    path('pricing/', pages.SystemPageView.as_view(slug='pricing'), name='page.pricing'),
    path('support/', pages.SystemPageView.as_view(slug='support'), name='page.support'),
    path('page/<slug:slug>/', pages.ShowPageView.as_view(), name='page'),
]

admin_patterns = [
    path('admin/', include(('eventyay.control.urls_admin', 'eventyay_admin'))),
]

orga_patterns = [
    path('orga/', include('eventyay.orga.urls')),
]

# Note: agenda and cfp patterns are now included under {organizer}/{event} in maindomain_urlconf.py
# They are no longer at the root level

debug_patterns = []

if settings.DEBUG and importlib.util.find_spec('debug_toolbar') and 'debug_toolbar' in settings.INSTALLED_APPS:
    debug_patterns.append(path('__debug__/', include('debug_toolbar.urls')))
    debug_patterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common_patterns = (
    base_patterns
    + control_patterns
    + debug_patterns
    + eventyay_common_patterns
    + page_patterns
    + admin_patterns
    + orga_patterns
)
