# Generated by Django 3.1.4 on 2021-03-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0055_unset_is_featured_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewscorecategory",
            name="is_independent",
            field=models.BooleanField(default=False),
        ),
    ]
