# Generated by Django 3.2.4 on 2021-10-25 14:29

from django.db import migrations
import i18nfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0059_remove_question_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeroption",
            name="answer",
            field=i18nfield.fields.I18nCharField(),
        ),
    ]
