# Generated by Django 3.2.10 on 2022-10-29 09:41

from django.db import migrations, models

import pretalx.submission.models.resource


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0068_alter_reviewscore_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="link",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource",
            field=models.FileField(
                null=True, upload_to=pretalx.submission.models.resource.resource_path
            ),
        ),
    ]
