# Generated by Django 5.1.1 on 2024-10-03 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0076_submissionfavourite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubmissionFavourite",
            new_name="SubmissionFavouriteDeprecated",
        ),
    ]
