# Generated by Django 5.1.1 on 2024-10-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0077_answeroption_position"),
        ("submission", "0079_alter_submissionfavourite_unique_together"),
    ]

    operations = []
