# Generated by Django 5.1.7 on 2025-04-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0080_submissioncomment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="public",
            new_name="is_public",
        ),
    ]
