# Generated by Django 3.0.5 on 2020-04-16 07:24

import uuid

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "token_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                ("event_id", models.CharField(db_index=True, max_length=200)),
                ("profile", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "traits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        size=None,
                    ),
                ),
            ],
            options={"unique_together": {("token_id", "event_id")},},
        ),
    ]
