# Generated by Django 3.0.5 on 2020-04-16 08:21

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatEvent",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("event_id", models.CharField(db_index=True, max_length=200)),
                ("channel", models.CharField(db_index=True, max_length=300)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.CharField(max_length=200)),
                ("content", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.User",
                    ),
                ),
            ],
        ),
    ]
