# Generated by Django 3.0.5 on 2020-04-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_chatevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="client_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("token_id", "event_id"), ("client_id", "event_id")},
        ),
    ]
