# Generated by Django 3.0.5 on 2020-04-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20200416_1546"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("world_id", models.CharField(db_index=True, max_length=200)),
                ("channel", models.CharField(db_index=True, max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.User",
                    ),
                ),
            ],
            options={"unique_together": {("user", "channel")},},
        ),
    ]
