GROUP_USER = "user.{id}"
GROUP_WORLD = "world.{id}"
GROUP_CHAT = "chat.{channel}"
GROUP_VERSION = "version.{label}"
GROUP_ROOM = "room.{id}"
GROUP_ROOM_QUESTION_READ = "room.{id}.question.read"
GROUP_ROOM_QUESTION_MODERATE = "room.{id}.question.moderate"
