# Generated by Django 3.0.5 on 2020-04-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="world",
            name="domain",
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
