# Generated by Django 3.0.5 on 2020-04-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_world_domain"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ("import_id", "name")},
        ),
        migrations.AddField(
            model_name="room",
            name="sorting_priority",
            field=models.IntegerField(default=0),
        ),
    ]
