# Generated by Django 3.0.6 on 2020-05-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="world",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
