# Generated by Django 3.0.5 on 2020-05-26 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_reaction_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatevent",
            name="edited",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="chatevent",
            name="replaces",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replaced_by",
                to="core.ChatEvent",
            ),
        ),
    ]
