# Generated by Django 3.0.6 on 2020-05-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20200526_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="world",
            name="locale",
            field=models.CharField(default="en", max_length=100),
        ),
    ]
