# Generated by Django 3.0.6 on 2020-06-20 10:24

from django.db import migrations


def migrate_about(apps, schema_editor):
    World = apps.get_model("core", "World")
    Room = apps.get_model("core", "Room")

    for w in World.objects.all():
        Room.objects.create(
            world=w,
            name="Startseite" if w.locale == "de" else "About",
            sorting_priority=-1,
            module_config=[{"type": "page.markdown", "config": {"content": w.about}}],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_world_timezone"),
    ]

    operations = [
        migrations.RunPython(migrate_about),
        migrations.RemoveField(
            model_name="world",
            name="about",
        ),
    ]
