# Generated by Django 3.0.6 on 2020-07-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_room_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="room", name="pretalx_id", field=models.IntegerField(default=0),
        ),
    ]
