# Generated by Django 3.0.8 on 2020-07-13 14:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_bbbcall_bbbserver"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exhibitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=300, null=True)),
                ("description", models.CharField(max_length=500, null=True)),
                ("text", models.TextField(null=True)),
                ("grid_color", models.CharField(max_length=6, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibitors",
                        to="core.Room",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibitors",
                        to="core.World",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExhibitorStaff",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exhibitor",
                    models.ForeignKey(
                        max_length=300,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="core.Exhibitor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exhibitor_staff",
                        to="core.User",
                    ),
                ),
            ],
            options={"unique_together": {("user", "exhibitor")},},
        ),
    ]
