# Generated by Django 3.0.6 on 2020-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_user_blocked_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="bbbcall",
            name="invited_members",
            field=models.ManyToManyField(related_name="bbb_invites", to="core.User"),
        ),
        migrations.AlterField(
            model_name="user",
            name="blocked_users",
            field=models.ManyToManyField(related_name="blocked_by", to="core.User"),
        ),
    ]
