# Generated by Django 3.0.8 on 2020-07-16 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_exhibitor_exhibitorstaff"),
    ]

    operations = [
        migrations.RemoveField(model_name="exhibitor", name="grid_color",),
        migrations.AddField(
            model_name="exhibitor",
            name="header_img",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exhibitor",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exhibitor", name="size", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exhibitor",
            name="sorting_priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="exhibitorstaff",
            name="exhibitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="core.Exhibitor",
            ),
        ),
        migrations.CreateModel(
            name="ExhibitorSocialMediaLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_text", models.CharField(max_length=300)),
                ("url", models.URLField()),
                (
                    "exhibitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_links",
                        to="core.Exhibitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExhibitorLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_text", models.CharField(max_length=300)),
                ("url", models.URLField()),
                (
                    "exhibitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="core.Exhibitor",
                    ),
                ),
            ],
        ),
    ]
