# Generated by Django 3.0.8 on 2020-07-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_auto_20200716_1608"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitor",
            name="size",
            field=models.CharField(
                choices=[("1x1", "S"), ("3x1", "M"), ("3x3", "L")],
                default="1x1",
                max_length=3,
            ),
        ),
    ]
