# Generated by Django 3.0.8 on 2020-07-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_auto_20200723_0921"),
    ]

    operations = [
        migrations.RemoveField(model_name="exhibitor", name="description",),
        migrations.AddField(
            model_name="exhibitor",
            name="short_text",
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="exhibitor",
            name="tagline",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="exhibitor",
            name="name",
            field=models.CharField(max_length=80, null=True),
        ),
    ]
