# Generated by Django 3.0.5 on 2020-07-31 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_membership_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="bbbcall",
            name="guest_policy",
            field=models.CharField(default="ALWAYS_ACCEPT", max_length=50),
        ),
        migrations.AddField(
            model_name="bbbcall",
            name="voice_bridge",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="bbbserver",
            name="rooms_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bbbserver",
            name="world_exclusive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.World",
            ),
        ),
    ]
