# Generated by Django 3.0.8 on 2020-07-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20200723_1106"),
    ]

    operations = [
        migrations.RemoveField(model_name="exhibitor", name="header_img",),
    ]
