# Generated by Django 3.0.6 on 2020-08-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20200731_1307"),
    ]

    operations = [
        migrations.AddField(
            model_name="bbbserver",
            name="cost",
            field=models.IntegerField(default=0),
        ),
    ]
