# Generated by Django 3.0.5 on 2020-08-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_bbbserver_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="force_join",
            field=models.BooleanField(default=False),
        ),
    ]
