# Generated by Django 3.0.8 on 2020-08-03 10:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_room_force_join"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exhibitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=80, null=True)),
                ("tagline", models.CharField(max_length=250, null=True)),
                ("short_text", models.TextField(max_length=500, null=True)),
                ("logo", models.URLField(blank=True, null=True)),
                ("text", models.TextField(null=True)),
                (
                    "size",
                    models.CharField(
                        choices=[("1x1", "S"), ("3x1", "M"), ("3x3", "L")],
                        default="1x1",
                        max_length=3,
                    ),
                ),
                ("sorting_priority", models.IntegerField(default=0)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibitors",
                        to="core.Room",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibitors",
                        to="core.World",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExhibitorSocialMediaLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_text", models.CharField(max_length=300)),
                ("url", models.URLField()),
                (
                    "exhibitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_links",
                        to="core.Exhibitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExhibitorLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_text", models.CharField(max_length=300)),
                ("url", models.URLField()),
                (
                    "exhibitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="core.Exhibitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExhibitorStaff",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exhibitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="core.Exhibitor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exhibitor_staff",
                        to="core.User",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "exhibitor")},
            },
        ),
    ]
