# Generated by Django 3.0.8 on 2020-08-14 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_contactrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="answered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exhibitor_answered_contact_requests",
                to="core.User",
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
