# Generated by Django 3.0.6 on 2020-08-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_contactrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitor",
            name="banner_detail",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exhibitor",
            name="banner_list",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exhibitor",
            name="contact_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
