# Generated by Django 3.0.6 on 2020-08-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_auto_20200820_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitorlink",
            name="category",
            field=models.CharField(
                choices=[("profile", "Profile"), ("download", "Download")],
                default="profile",
                max_length=32,
            ),
        ),
    ]
