# Generated by Django 3.0.5 on 2020-11-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_auto_20200929_2056"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitor",
            name="highlighted_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="highlighted_by_exhibitors",
                to="core.Room",
            ),
        ),
    ]
