# Generated by Django 3.0.6 on 2020-12-14 20:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_question_questionvote"),
    ]

    operations = [
        migrations.CreateModel(
            name="JanusServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("url", models.URLField()),
                ("room_create_key", models.CharField(max_length=300)),
                (
                    "world_exclusive",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.World",
                    ),
                ),
            ],
        ),
    ]
