# Generated by Django 3.1.4 on 2020-12-28 17:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_chateventreaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="TurnServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("hostname", models.CharField(max_length=300)),
                ("auth_secret", models.CharField(max_length=300)),
                (
                    "world_exclusive",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.world",
                    ),
                ),
            ],
        ),
    ]
