# Generated by Django 3.0.11 on 2021-01-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_turnserver"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
