# Generated by Django 3.1.5 on 2021-01-26 14:09

from django.db import migrations, models

import venueless.core.models.exhibitor


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_question_is_pinned"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exhibitor",
            old_name="text",
            new_name="text_legacy",
        ),
        migrations.AddField(
            model_name="exhibitor",
            name="text_content",
            field=models.JSONField(
                default=venueless.core.models.exhibitor.default_text
            ),
        ),
    ]
