# Generated by Django 3.1.5 on 2021-03-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_roulettepairing_rouletterequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
