# Generated by Django 3.1.8 on 2021-07-20 20:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_auto_20210610_1700"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamingServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=300)),
                ("token_secret", models.CharField(max_length=300)),
                (
                    "url_input",
                    models.CharField(
                        default="rtmp://server/app/{name}?token={token}", max_length=300
                    ),
                ),
                (
                    "url_output",
                    models.CharField(
                        default="https://server/hls/{name}.m3u8", max_length=300
                    ),
                ),
            ],
        ),
    ]
