# Generated by Django 3.2.4 on 2021-10-16 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_poster_posterlink_posterpresenter_postervote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poster",
            name="chat_room",
        ),
        migrations.AddField(
            model_name="poster",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posters",
                to="core.channel",
            ),
        ),
    ]
