# Generated by Django 3.2.5 on 2021-10-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_auto_20211016_1643"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="import_id",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
