# Generated by Django 3.2.12 on 2022-02-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_pretalx_permissions_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="world",
            name="external_auth_url",
            field=models.URLField(null=True, blank=True),
        ),
    ]
