# Generated by Django 3.2.12 on 2022-03-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_auto_20220214_2103"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="category",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="poster",
            name="schedule_session",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="poster",
            name="title",
            field=models.TextField(null=True),
        ),
    ]
