# Generated by Django 3.2.15 on 2022-09-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_user_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_login_id_linkedin",
            field=models.CharField(
                blank=True, db_index=True, max_length=190, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_login_id_twitter",
            field=models.CharField(
                blank=True, db_index=True, max_length=190, null=True
            ),
        ),
    ]
