# Generated by Django 3.2.15 on 2023-02-05 17:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_auto_20220927_1553"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="client_state",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
