# Generated by Django 3.2.18 on 2023-03-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_user_client_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("person", "Person"), ("kiosk", "Kiosk")],
                default="person",
                max_length=8,
            ),
        ),
    ]
