# Generated by Django 3.2.20 on 2023-08-05 15:37

import django.db.models.deletion
from django.db import migrations, models

import venueless.core.models.room


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_user_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="world",
            options={"ordering": ("id",)},
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("person", "Person"),
                    ("kiosk", "Kiosk"),
                    ("anon", "Anonymous"),
                ],
                default="person",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="AnonymousInvite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_token",
                    models.CharField(
                        db_index=True,
                        default=venueless.core.models.room.generate_short_token,
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("expires", models.DateTimeField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anonymous_invites",
                        to="core.room",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anonymous_invites",
                        to="core.world",
                    ),
                ),
            ],
        ),
    ]
