# Generated by Django 4.2.13 on 2024-07-18 01:31

import django.db.models.deletion
from django.db import migrations, models

import venueless.core.models.room
import venueless.core.models.world
import venueless.core.utils.json


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_auto_20230805_1737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatevent",
            name="content",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="room",
            name="module_config",
            field=models.JSONField(
                default=venueless.core.models.room.empty_module_config,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="schedule_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="trait_grants",
            field=models.JSONField(
                blank=True,
                default=venueless.core.models.room.default_grants,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="client_state",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="world",
            name="config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="world",
            name="feature_flags",
            field=models.JSONField(
                blank=True,
                default=venueless.core.models.world.default_feature_flags,
            ),
        ),
        migrations.AlterField(
            model_name="world",
            name="roles",
            field=models.JSONField(
                blank=True,
                default=venueless.core.models.world.default_roles,
                encoder=venueless.core.utils.json.CustomJSONEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="world",
            name="trait_grants",
            field=models.JSONField(
                blank=True,
                default=venueless.core.models.world.default_grants,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ChatEventNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.chatevent",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_notifications",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Event Notification",
                "verbose_name_plural": "Chat Event Notifications",
            },
        ),
    ]
