name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system packages
        run: sudo apt update && sudo apt install libffi-dev libssl-dev libxml2-dev libxslt1-dev libenchant1c2a gettext libfreetype-dev libjpeg-dev

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: doc
      
      - name: Build documentation
        run: make html
        working-directory: doc  # Adjust to your Sphinx docs directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/html