# Generated by Django 4.2.16 on 2024-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0001_initial'),
        ('badges', '0004_alter_badgelayout_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgelayout',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='badge_layouts',
                to='pretixbase.itemcategory',
                verbose_name='Category'
            ),
        ),
    ]